### PR TITLE
fixed EINVAL not declared issue

### PR DESCRIPTION
**Pull request by ttsesm**
added EINVAL missing declaration

### CODE REVIEW

**Comment by sampotter** [comment]
Looks good, but please use spaces instead of tabs (and make sure to use 4 spaces per tab).

**Comment by ttsesm** [comment]
Grrrr!!!! I do not know what is happening I am trying to change the spacing but each time it is different.

**Comment by ttsesm** [comment]
Ok, it should be fine now ;-)

**Comment by sampotter** [comment]
Thanks for fixing the whitespace! :-) I'm going to go ahead and merge it.

**Pull request merged**
