### PR TITLE
Windows Wheels

### PR DESCRIPTION
**Pull request by mikedh**

### CODE REVIEW

**Comment by mikedh** [comment]
Ah, accidentally screwed up this PR in a conflict resolution; [this commit](https://github.com/sampotter/python-embree/commit/87f07aecfd9e40e1135cfbef7861637f38ca78eb) was supposed to be this PR.

- Windows wheels building. The `aligned_free` stuff is because unit tests were failing on Windows (probably https://github.com/sampotter/python-embree/issues/10) 
- Releasing on to PyPi [here](https://pypi.org/project/embree/#files). The reason the build on master failed was because I apparently can't add a `PYPI_TOKEN` secret without being an admin (I can send you the secret to add via magic-wormhole or similar)

**Comment by sampotter** [comment]
@mikedh Could you go ahead and add me as a maintainer to to PyPI project? My profile is here: https://pypi.org/user/sampotter/

**Comment by mikedh** [comment]
Added you as an owner! If you add your `PYPI_TOKEN` I'll deauthorize the one I've been using in my upstream repo and then all releases will come from the master branch of this repo.

**Comment by sampotter** [comment]
Link for docs explaining how to do this?

**Comment by mikedh** [comment]
On PyPi to generate the token it's under Account Settings -> Add API Token

On GitHub it's in the repo settings (hidden in the little ribbon under the repo name) Secrets -> Actions -> New repository secret. I think this guide is relevant: https://docs.github.com/en/actions/security-guides/encrypted-secrets

**Comment by mikedh** [comment]
No worries! Looks like the re-build didn't want to release:

```
Error during upload. Retry with the --verbose option for more details.
HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
Invalid or non-existent authentication information. See https://pypi.org/help/#invalid-auth for more information.
```

It suggests checking to make sure there's not a newline copied into the secret. It could also be the version already exists,  for every commit/PR to master the release to PyPi will fail if this isn't incremented:
https://github.com/sampotter/python-embree/blob/87f07aecfd9e40e1135cfbef7861637f38ca78eb/embree.pyx#L12

I released it with a `0.0.4` tag on my fork, so you might want to try double-checking that secret and then doing a simple commit incrementing version to `0.0.5` to trigger the re-build. Thanks for messing around with this!

**Comment by sampotter** [comment]
Yep, thanks for coaching me through this! Busy the rest of the day but I'll dig into this tomorrow morning.

**Pull request closed without merging**
